scheduling-policy: (LIFO/FIFO)
  The order we proritize collectives according based on their time of arrival. LIFO means that most recently created collectives have higher priority. While FIFO is the reverse.
endpoint-delay: (int)
  The time NPU spends processing a message after receiving it in terms of cycles.
active-chunks-per-dimension:: (int)
  This corresponds to the Maximum number of chunks we like execute in parallel on each logical dimesnion of topology.
preferred-dataset-splits: (int)
  The number of chunks we divide each collective into.
boost-mode: (0/1)
  0 means all nodes are simulated. 1 means that only the nodes directly engaged with node 0 (node 0 collects all of the stats) are simulated. It is a technique to reduce the simulation time by trading some (minor) accuracy.
all-reduce-implementation:: (Dimension0Collective_Dimension1Collective_..._DimensionNCollective)
  Here we can create a multiphase colective all-reduce algorithm and directly specify the collective algorithm type for each logical dimension. The available options (algorithms) are: ring, direct, doubleBinaryTree, oneRing, oneDirect.
reduce-scatter-implementation:: (Dimension0CollectiveAlg_Dimension1CollectiveAlg_..._DimensionNCollectiveAlg)
  The same as "all-reduce-implementation:" but for reduce-scatter collective. The available options (algorithms) are: ring, direct, oneRing, oneDirect.
all-gather-implementation:: (Dimension0CollectiveAlg_Dimension1CollectiveAlg_..._DimensionNCollectiveAlg)
  The same as "all-reduce-implementation:" but for all-gather collective. The available options (algorithms) are: ring, direct, oneRing, oneDirect.
all-to-all-implementation:: (Dimension0CollectiveAlg_Dimension1CollectiveAlg_..._DimensionNCollectiveAlg)
  The same as "all-reduce-implementation:" but for all-to-all collective. The available options (algorithms) are: ring, direct, oneRing, oneDirect.
collective-optimization: (baseline/localBWAware)
  NOTE: The default clock cycle period is 1ns (1 Ghz feq). This value is defined inside Sys.hh. One can change it to any number. It will be a configurable command line parameter in the later versions.



